FUNÇÃO: FPS ON
RegisterCommand("fps",function(source,args)
    if args[1] == nil then
        TriggerEvent("Notify","sucesso","Escolha qual o nivel de Boost voce deseja:") 
        TriggerEvent("Notify","sucesso","1 - /fps ultra = FPS mais alto que seu PC pode chegar;")
        TriggerEvent("Notify","sucesso","2 - /fps medio = Configuração mediana para não perder tanta qualidade;")
        TriggerEvent("Notify","sucesso","3 - /fps baixo = Desativa só alguns efeitos visuais;")
        TriggerEvent("Notify","sucesso","4- /fps off para desativar todos os eveitos e tornar padrão.")
        TriggerEvent("Notify","sucesso","Se tu leu isso tu é boiola pra carai.")
    elseif args[1] == "on" then
        TriggerEvent("Notify","sucesso","Escolha qual o nivel de Boost voce deseja:") 
        TriggerEvent("Notify","sucesso","1 - /fps ultra = FPS mais alto que seu PC pode chegar;")
        TriggerEvent("Notify","sucesso","2 - /fps medio = Configuração mediana para não perder tanta qualidade;")
        TriggerEvent("Notify","sucesso","3 - /fps baixo = Desativa só alguns efeitos visuais;")
        TriggerEvent("Notify","sucesso","4- /fps off para desativar todos os eveitos e tornar padrão.")
        TriggerEvent("Notify","sucesso","Se tu leu isso tu é boiola pra carai.")
   elseif args[1] == "ultra" then
        SetTimecycleModifier("cinema")
        RopeDrawShadowEnabled(false)
        CascadeShadowsClearShadowSampleType()
        CascadeShadowsSetAircraftMode(false)
        CascadeShadowsEnableEntityTracker(true)
        CascadeShadowsSetDynamicDepthMode(false)
        CascadeShadowsSetEntityTrackerScale(0.0)
        CascadeShadowsSetDynamicDepthValue(0.0)
        CascadeShadowsSetCascadeBoundsScale(0.0)
        SetFlashLightFadeDistance(0.0)
        SetLightsCutoffDistanceTweak(0.0)
        DistantCopCarSirens(false)
        TriggerEvent("Notify","sucesso","Boost de fps ultra ligado!")
    elseif args[1] == "medio" then
        SetTimecycleModifier("cinema")
        RopeDrawShadowEnabled(false)
        CascadeShadowsClearShadowSampleType()
        CascadeShadowsSetAircraftMode(false)
        CascadeShadowsEnableEntityTracker(true)
        CascadeShadowsSetDynamicDepthMode(false)
        CascadeShadowsSetEntityTrackerScale(0.0)
        CascadeShadowsSetDynamicDepthValue(0.0)
        CascadeShadowsSetCascadeBoundsScale(0.0)
        SetFlashLightFadeDistance(0.0)
        SetLightsCutoffDistanceTweak(0.0)
        DistantCopCarSirens(false)
        TriggerEvent("Notify","sucesso","Boost de fps mediano ligado!")
    elseif args[1] == "baixo" then
        RopeDrawShadowEnabled(true)
        CascadeShadowsClearShadowSampleType()
        CascadeShadowsSetAircraftMode(false)
        CascadeShadowsEnableEntityTracker(true)
        CascadeShadowsSetDynamicDepthMode(false)
        CascadeShadowsSetEntityTrackerScale(5.0)
        CascadeShadowsSetDynamicDepthValue(3.0)
        CascadeShadowsSetCascadeBoundsScale(3.0)
        SetFlashLightFadeDistance(3.0)
        SetLightsCutoffDistanceTweak(3.0)
        DistantCopCarSirens(false)
        SetArtificialLightsState(false)
        TriggerEvent("Notify","sucesso","Boost de fps baixo ligado!")
    elseif args[1] == "off" then
        SetTimecycleModifier("default")
        RopeDrawShadowEnabled(true)
        CascadeShadowsSetAircraftMode(true)
        CascadeShadowsEnableEntityTracker(false)
        CascadeShadowsSetDynamicDepthMode(true)
        CascadeShadowsSetEntityTrackerScale(5.0)
        CascadeShadowsSetDynamicDepthValue(5.0)
        CascadeShadowsSetCascadeBoundsScale(5.0)
        SetFlashLightFadeDistance(10.0)
        SetLightsCutoffDistanceTweak(10.0)
        DistantCopCarSirens(true)
        SetArtificialLightsState(false)
        TriggerEvent("Notify","sucesso","Boost de fps desligado!")
    end
end)